server:
  port: ${SERVER_PORT:13100}

spring:
  application:
    name: config-server
  profiles:
    active: git

  cloud:
    config:
      server:
        git:
          uri: ${CONFIG_GIT_URI:https://github.com/89-49/configs}
          default-label: ${CONFIG_GIT_BRANCH:main}
          search-paths:
            - common
            - "{application}"
            - "{application}/{profile}"
          basedir: ${CONFIG_BASEDIR:tmp/configs}
          clone-on-start: true

eureka:
  instance:
    prefer-ip-address: false
    hostname: ${HOSTNAME:localhost}

  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:13101/eureka/}

management:
  endpoints:
    web:
      exposure:
        include: refresh,health,info,metrics

#  zipkin은 후순위이므로 주석 처리

#  tracing:
#    sampling:
#      probability: 0.1
#    zipkin:
#      tracing:
#        endpoint: "${ZIPKIN_ENDPOINT:http://localhost:9411/api/v2/spans}"